[libraries]
jackson-annotations = "com.fasterxml.jackson.core:jackson-annotations:2.13.3"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.13.3"
jackson-datatype-jsr310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.3"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.13.3"
ktor-client-cio = "io.ktor:ktor-client-cio:2.0.1"
ktor-client-core = "io.ktor:ktor-client-core:2.0.1"
ktor-client-content-negotiation = "io.ktor:ktor-client-content-negotiation:2.0.1"
ktor-client-logging = "io.ktor:ktor-client-logging:2.0.1"
ktor-client-mock = "io.ktor:ktor-client-mock:2.0.1"
ktor-serialization-jackson = "io.ktor:ktor-serialization-jackson:2.0.1"
ktorm-core = "org.ktorm:ktorm-core:3.4.1"
liquibase-core = "org.liquibase:liquibase-core:4.10.0"
mockk = "io.mockk:mockk:1.12.4"
rider-junit5 = "com.github.database-rider:rider-junit5:1.32.3"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.2"
