[libraries]
jackson-annotations = "com.fasterxml.jackson.core:jackson-annotations:2.13.4"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.13.4"
jackson-datatype-jsr310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.13.4"
ktor-client-cio = "io.ktor:ktor-client-cio:2.1.1"
ktor-client-core = "io.ktor:ktor-client-core:2.1.1"
ktor-client-content-negotiation = "io.ktor:ktor-client-content-negotiation:2.1.1"
ktor-client-logging = "io.ktor:ktor-client-logging:2.1.1"
ktor-client-mock = "io.ktor:ktor-client-mock:2.1.1"
ktor-serialization-jackson = "io.ktor:ktor-serialization-jackson:2.1.1"
ktorm-core = "org.ktorm:ktorm-core:3.5.0"
liquibase-core = "org.liquibase:liquibase-core:4.15.0"
mockk = "io.mockk:mockk:1.12.7"
rider-junit5 = "com.github.database-rider:rider-junit5:1.34.0"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.3"
