[libraries]
jackson-annotations = "com.fasterxml.jackson.core:jackson-annotations:2.14.1"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.14.1"
jackson-datatype-jsr310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.1"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.14.1"
ktor-client-core = "io.ktor:ktor-client-core:2.2.2"
ktor-client-content-negotiation = "io.ktor:ktor-client-content-negotiation:2.2.2"
ktor-client-logging = "io.ktor:ktor-client-logging:2.2.2"
ktor-client-mock = "io.ktor:ktor-client-mock:2.2.2"
ktor-client-okhttp = "io.ktor:ktor-client-okhttp:2.2.2"
ktor-serialization-jackson = "io.ktor:ktor-serialization-jackson:2.2.2"
ktorm-core = "org.ktorm:ktorm-core:3.5.0"
mockk = "io.mockk:mockk:1.13.3"
mockwebserver = "com.squareup.okhttp3:mockwebserver:4.10.0"
liquibase-core = "org.liquibase:liquibase-core:4.18.0"
rider-junit5 = "com.github.database-rider:rider-junit5:1.35.1"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.6"
